spring:
  cloud:
    function:
      definition: paymentProcessor
    stream:
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: CH#1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083
